
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jul 13 16:08:21 COT 2013
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class simbolos {
  /* terminals */
  public static final int SUM = 2;
  public static final int PC = 10;
  public static final int PA = 9;
  public static final int iden = 7;
  public static final int EOF = 0;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int Numero = 8;
  public static final int MUL = 4;
  public static final int IGL = 6;
  public static final int MIN = 3;
}

